JNG-3176 Add workflows and update pom.xml
BlackBeltTechnology/karaf-jasypt-support pull request #1
Opened 2022-01-25 16:22 UTC by FarkasValentin

2022-01-27 15:53 UTC, robertcsakany requested changes

2022-01-27 15:53 UTC, robertcsakany commented on .flattened-pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file have to be removed and added to .gitignore

2022-01-27 15:53 UTC, robertcsakany commented on pom.xml
>              </plugin>
Karaf commands intruction and imports cannot be removed.

2022-01-28 16:49 UTC, noherczeg approved these changes

2022-01-31 08:06 UTC, merged